name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add repo for swi-prolog
      run: apt-add-repository ppa:swi-prolog/devel -y    
    
    - name: Add repo for swi-prolog
      run: apt-get update -q

    - name: Install swipl
      run: apt-get install swi-prolog-nox
    
    - name: Run test
      run: make test

    - name: Run distcheck
      run: make distcheck
